CREATE DATABASE D_CLONE;
-- DROP DATABASE D_CLONE;

CREATE TABLE USERS (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(24) NOT NULL,
    FULL_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASS_HASH VARCHAR(64) NOT NULL,
    SALT VARCHAR(12) NOT NULL,
    PFP_URL TEXT,
    ABOUT TEXT,
    HEX_COLOR CHAR(6),
    DATE_JOINED DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SERVERS (
    ID SERIAL PRIMARY KEY,
    SERVER_NAME VARCHAR(128) NOT NULL,
    PFP_URL TEXT,
    CREATOR_ID BIGINT NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT SERVER_CREATOR_FK FOREIGN KEY (CREATOR_ID) REFERENCES USERS (ID)
);

CREATE TABLE MEMBERS (
    USER_ID BIGINT NOT NULL,
    SERVER_ID BIGINT NOT NULL,
    JOIN_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
        CONSTRAINT SERVER_ID_FK FOREIGN KEY (SERVER_ID) REFERENCES SERVERS (ID)
);

CREATE TABLE MEMBER_ROLES(
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
        CONSTRAINT MEMBER_ROLES_USERS_FK FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
        CONSTRAINT MEMBER_ROLES_ROLES_FK FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID)
);

CREATE TABLE CHANNELS (
    ID SERIAL PRIMARY KEY,
    SERVER_ID BIGINT,
        CONSTRAINT SERVER_CHANNELS_ID_FK FOREIGN KEY (SERVER_ID) REFERENCES SERVERS (ID)
);

CREATE TABLE ROLES (
    ID SERIAL PRIMARY KEY,
    ROLE_NAME VARCHAR(64) NOT NULL,
    HEX_COLOR CHAR(6)
);

CREATE TABLE PERMISSIONS(
    ID SERIAL PRIMARY KEY,
    PERMISSION_NAME VARCHAR(64) NOT NULL
);

CREATE TABLE ROLE_PERMISSIONS (
    ROLE_ID BIGINT NOT NULL,
    PERMISSION_ID BIGINT NOT NULL,
        CONSTRAINT ROLE_PERMISSIONS_ROLES_FK FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID),
        CONSTRAINT ROLE_PERMISSIONS_PERMISSIONS_FK FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSIONS (ID)
);

CREATE TABLE MESSAGES (
    ID SERIAL PRIMARY KEY,
    SENDER_ID BIGINT NOT NULL,
    MESSAGE TEXT NOT NULL,
    SENT_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    RECEIVED_DATE TIMESTAMP,
        CONSTRAINT MESSAGE_SENDERS_FK FOREIGN KEY (SENDER_ID) REFERENCES USERS (ID)
);

CREATE VIEW MESSAGE_CARD AS
    SELECT
        U.ID AS USER_ID, U.PFP_URL, U.USERNAME,
        M.ID AS MESSAGE_ID, M.MESSAGE, M.SENT_DATE
    FROM USERS U
    JOIN MESSAGES M ON U.ID = M.SENDER_ID;

    SELECT CURRENT_TIMESTAMP AS TODAY;



-- TEST DATE

CREATE TABLE DATE_FORMAT_TEST(
    TEST_DATE TIMESTAMP NOT NULL
);

INSERT INTO DATE_FORMAT_TEST VALUES ('2024-2-22 3:20:23.1555');

SELECT * FROM DATE_FORMAT_TEST;