-- CREATE DATABASE D_CLONE;
-- FOR REFERENCE ONLY

CREATE TABLE
    USERS(
        ID SERIAL PRIMARY KEY,
        USER_NAME VARCHAR(64) NOT NULL UNIQUE,
        EMAIL VARCHAR(255) NOT NULL,
        PASSWORD TEXT NOT NULL,
        BIRTH_DATE DATE NOT NULL,
        NEWSLETTER BOOLEAN DEFAULT FALSE,
        CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        ONLINE_STATUS SMALLINT,
        ACCOUNT_STATUS SMALLINT,
        CONSTRAINT CHECK_ONLINE_STATUS CHECK(
            ONLINE_STATUS BETWEEN 0 AND 4
        ),
        CONSTRAINT CHECK_ACCOUNT_STATUS CHECK(
            ACCOUNT_STATUS BETWEEN 0 AND 2
        )
    );

INSERT INTO USERS (
    USER_NAME,
    EMAIL,
    PASSWORD,
    BIRTH_DATE,
    NEWSLETTER,
    ONLINE_STATUS,
    ACCOUNT_STATUS
)VALUES(
    'rubiel_god',
    'rubiel.perez@utp.ac.pa',
    'packet-tracer-god-ifconfig',
    '1903-11-03',
    TRUE,
    0,
    0
);

CREATE TABLE
    SESSIONS(
        ID SERIAL PRIMARY KEY,
        USER_ID BIGINT,
        ACTIVITY_TYPE SMALLINT,
        DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT USERS_SESSIONS_FK FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
    );