INSERT INTO USERS (
    USERNAME,
    FULL_NAME,
    EMAIL,
    PASS_HASH,
    SALT,
    PFP_URL,
    ABOUT,
    HEX_COLOR,
    DATE_JOINED
) VALUES (
    '',--max 24
    '', --max 255
    '', --max 255
    '', --max 64
    '', --max 12
    '', --url
    '', --text
    '' --hex color,
    '' --date
);

INSERT INTO SERVERS (
    SERVER_NAME,
    CREATOR_ID,
    CREATION_DATE
) VALUES (
    '', --max 128
    '', --url
    0, --user id
    '', --date
);

CREATE TABLE SERVER_MEMBERS (
    SERVER_ID,
    JOIN_DATE
) VALUES (
    0, --server id
    '', --date
);

CREATE TABLE ROLES (
    ID SERIAL PRIMARY KEY,
    ROLE_NAME VARCHAR(64) NOT NULL,
    HEX_COLOR CHAR(6)
);

CREATE TABLE MEMBER_ROLES(
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
        CONSTRAINT MEMBER_ROLES_USERS_FK FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
        CONSTRAINT MEMBER_ROLES_ROLES_FK FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID)
);

CREATE TABLE CHANNELS (
    ID SERIAL PRIMARY KEY,
    SERVER_ID BIGINT,
    CHANNEL_NAME VARCHAR(128) NOT NULL,
    CHANNEL_TYPE INT NOT NULL,
        CONSTRAINT SERVER_CHANNELS_ID_FK FOREIGN KEY (SERVER_ID) REFERENCES SERVERS (ID)
);

CREATE TABLE CHANNEL_ROLE_ACCESSIBILITY (
    CHANNEL_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
        CONSTRAINT CHANNEL_MEMBERS_CHANNELS_FK FOREIGN KEY (CHANNEL_ID) REFERENCES CHANNELS (ID),
            CONSTRAINT CHANNEL_MEMBERS_ROLES_FK FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) 
)

CREATE TABLE PERMISSIONS(
    ID SERIAL PRIMARY KEY,
    PERMISSION_NAME VARCHAR(64) NOT NULL
);

CREATE TABLE ROLE_PERMISSIONS (
    ROLE_ID BIGINT NOT NULL,
    PERMISSION_ID BIGINT NOT NULL,
        CONSTRAINT ROLE_PERMISSIONS_ROLES_FK FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID),
        CONSTRAINT ROLE_PERMISSIONS_PERMISSIONS_FK FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSIONS (ID)
);

CREATE TABLE MESSAGES (
    ID SERIAL PRIMARY KEY,
    SENDER_ID BIGINT NOT NULL,
    MESSAGE TEXT NOT NULL,
    SENT_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    RECEIVED_DATE TIMESTAMP,
        CONSTRAINT MESSAGE_SENDERS_FK FOREIGN KEY (SENDER_ID) REFERENCES USERS (ID)
);